export default {
  index: 'Overview',
  'TryHackMe-Challenge-TheRoom': 'TryHackMe — The Room (Tetrix)',
  'TryHackMe-Challenge-Grep': 'TryHackMe — Grep (SearchME)',
  'TryHackMe-Challenge-Nmap': 'TryHackMe — Nmap Challenge',
  'TryHackMe-Challenge-MothersSecret': "TryHackMe — Mother's Secret",
  'TryHackMe-Challenge-Olympus': 'TryHackMe — Olympus',
  'TryHackMe-Challenge-BasicPentestingJT': 'TryHackMe — Basic Pentesting (JT)',
  'TryHackMe-Challenge-CheckMate': 'TryHackMe — CheckMate',
  'TryHackMe-Challenge-Injectics': 'TryHackMe — Injectics',
  'TryHackMe-Challenge-Order': 'TryHackMe — Order (repeating-key XOR)',
  'TryHackMe-Challenge-OperationSlither': 'TryHackMe — Operation Slither (OSINT)',
  'TryHackMe-Challenge-SchemeCatcher': 'TryHackMe — SchemeCatcher (heap pwn + kernel LPE)',
  'TryHackMe-Challenge-HellsKitchen': "TryHackMe — Hell's Kitchen (SQLi + WS RCE + local NFS root)",
  'TryHackMe-DifferentCTF': 'TryHackMe — Different CTF (Adana: decoy vhost + SUID)',
  'TryHackMe-Challenge-WhatsYourName': "TryHackMe — What's Your Name? (WorldWAP: stored XSS → CSRF)",
  'TryHackMe-Challenge-Flip': 'TryHackMe — Flip (AES-CBC bit-flip)',
  'TryHackMe-Challenge-Frankesqwen': "TryHackMe — Frankesqwen (LLM training-data extraction)",
  'TryHackMe-Challenge-Expose': 'TryHackMe — Expose (MQTT/1337 recon → SQLi → upload → SUID find)',
  'TryHackMe-Challenge-LookBack': 'TryHackMe — LookBack (Exchange ProxyShell)',
  'TryHackMe-Challenge-OperationColdStart': 'TryHackMe — Operation Cold Start (SSRF allow-list → tar wildcard root)',
  'TryHackMe-Challenge-BreachBlockerUnlocker': 'TryHackMe — BreachBlocker Unlocker (exposed main.py → per-char hash → OTP cookie replay)'
}
